### ISSUE TITLE
[Bug] Reload fails if there is no holograms

### ISSUE THREAD

**Issue by rm20killer** [AerWyn81/HeadBlocks#18]
HB Version: v2.4.1 
If there are no holograms and try to reload the reload fails with an error:

Steps to reproduce
1) turn off all holograms in the config
2) Start server
3) do the command /headblocks reload
4) see the error

console error:
```
[12:50:26] [Server thread/INFO]: RM20_ issued server command: /headblocks reload
[12:50:26] [Server thread/INFO]: SQLite storage properly connected!
[12:50:26] [Server thread/INFO]: Loaded 0 (+17 HeadDatabase heads) configuration heads!
[12:50:26] [Server thread/INFO]: Loaded 0 locations!
[12:50:26] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'headblocks' in plugin HeadBlocks v2.4.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-117]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2342) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2302) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.unldenis.hologram.HologramPool.updateSpawnDistance(double)" because "fr.aerwyn81.headblocks.utils.internal.HoloLibSingleton.hologramPool" is null
	at fr.aerwyn81.headblocks.utils.internal.HoloLibSingleton.updateViewDistance(HoloLibSingleton.java:19) ~[HeadBlocks-2.4.2.jar:?]
	at fr.aerwyn81.headblocks.commands.list.Reload.perform(Reload.java:43) ~[HeadBlocks-2.4.2.jar:?]
	at fr.aerwyn81.headblocks.commands.HBCommandExecutor.onCommand(HBCommandExecutor.java:94) ~[HeadBlocks-2.4.2.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by rm20killer** [comment]
Just noticed a new release with the fix
