### ISSUE TITLE
1.18.2 compability

### ISSUE THREAD

**Issue by sphings79** [AerWyn81/HeadBlocks#7]
```
[14:46:10] [Server thread/ERROR]: Error occurred while enabling HeadBlocks v1.6.1 (Is it up to date?)
--
1634 | java.lang.ExceptionInInitializerError: null
1635 | at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.NBTCompound.setBoolean(NBTCompound.java:384) ~[HeadBlocks-1.6.1.jar:?]
1636 | at fr.aerwyn81.headblocks.handlers.HeadHandler.loadHeads(HeadHandler.java:165) ~[HeadBlocks-1.6.1.jar:?]
1637 | at fr.aerwyn81.headblocks.handlers.HeadHandler.loadConfiguration(HeadHandler.java:54) ~[HeadBlocks-1.6.1.jar:?]
1638 | at fr.aerwyn81.headblocks.HeadBlocks.onEnable(HeadBlocks.java:120) ~[HeadBlocks-1.6.1.jar:?]
1639 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1640 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1641 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1642 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-220]
1643 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-220]
1644 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-220]
1645 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-220]
1646 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-220]
1647 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
1648 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
1649 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
1650 | Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredField(String)" because the return value of "fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.getClazz()" is null
1651 | at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:36) ~[HeadBlocks-1.6.1.jar:?]
1652 | ... 15 more
```

**Comment by AerWyn81** [comment]
Fixed in [#74812ad](https://github.com/AerWyn81/HeadBlocks/commit/74812adfb5e72fed3e054d70085e21c720f1fda9).

You can download a preview version [here](https://github.com/AerWyn81/HeadBlocks/releases/tag/1.6.2).

Thanks for your report!
